#!/bin/sh
base_path=/srv/gwas-app
app_path=$base_path/gwas-web-app
backend=$app_path/backend

python_env="/srv/py-venvs/current"
cd $backend
sh $python_env/bin/activate
export PYTHONPATH=$base_path/atgwas/src/:$app_path/
$python_env/bin/python __init__.py
#esac
